name: Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  run-tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Anki 24.6.3 (Qt6)
            python: 3.9
            environment: py39-anki24.6.3-qt6
      fail-fast: false

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pyqt5-dev-tools xvfb jq

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: pip install 'tox==3.28.0'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tests
        run: tox -vvve ${{ matrix.environment }} -- --forked --verbose
